### ISSUE TITLE
I didn't understand the function der_filterX() and der_filterY() in utils.py

### ISSUE THREAD

**Issue by mrsempress** [paeccher/Depth-Map-Prediction-from-Single-Image-in-Keras#1]
Paper says "$$\nabla x d_i$$ and $$\nabla y d_i$$are the horizontal and vertical image gradients of the difference."
In code, it use K.conv2d(d, der_filterX(), padding='same') to compute. Because poor fundation, I don't understand why use this code and why choose K.variable([[[[-1]], [[0]], [[1]]], [[[-2]], [[0]], [[2]]], [[[-1]], [[0]], [[1]]]]) and K.variable([[[[-1]], [[-2]], [[-1]]], [[[0]], [[0]], [[0]]], [[[1]], [[2]], [[1]]]]).

**Comment by paeccher** [comment]
They are called Sobel Filters and are used to compute the gradient of an image. You can refer to https://en.wikipedia.org/wiki/Sobel_operator to have more informations.

**Comment by mrsempress** [comment]
@paeccher Thanks.
